name: test
on: [push]
jobs:
  Run_tests:
    runs-on: ubuntu-latest 
    steps: 
      - uses: actions/checkout@v2
      - name: run test
        run: |
          pip install pytest
          pytest

      - name: build
        run: docker build -t guillaumegillet/testynov:test .

      - name: run
        run: docker run guillaumegillet/testynov:test

      - name: dockerhub
        env:
          ID: ${{secrets.ID}}
          MDP: ${{secrets.MDP}}
        run: |
          docker login -u $ID -p $MDP
          docker push guillaumegillet/testynov:test